# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: atikhobaev.github.com
email: atikhobaev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Здравствуйте, я Андрей Тихобаев — частный web-мастер, занимаюсь разработкой сайтов, от создания дизайна до верстки и полного запуска проекта.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://atikhobaev.github.com" # the base hostname & protocol for your site
twitter_username: atikhobaev
github_username:  atikhobaev

# Build settings
markdown: kramdown
